export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            margin: "1px",
            padding: "20px"
          }}
        >
          This is a header
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightgray",
            margin: "1px",
            padding: "20px"
          }}
        >
          This is a footer
        </footer>
      </body>
    </html>
  );
}
